### ISSUE TITLE
How to create nested objects on the fly?

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#120]
I have started developing a demo app for DunglasApiBundle. I tried to deserialize a new User with a new Group:

```
POST api/users

{"_format": "json",
"groups": [{
"name":"newgroup"
}],
"name": "test12311"
}
```

I have configured serialization groups, however, I'm receiving the following error:

```
hydra:title: "An error occurred"
hydra:description: "Nested objects for attribute "groups" of "AppBundle\Entity\User" are not enabled. Use serialization groups to change that behavior."
```

Here's my entity: https://github.com/felicitus/DunglasApiBundleDemo/blob/master/src/AppBundle/Entity/User.php

**Comment by dunglas** [comment]
Hi,

There was some issues I fixed in felicitus/DunglasApiBundleDemo#1:
- annotations where not enabled: https://github.com/felicitus/DunglasApiBundleDemo/pull/1/files#diff-bf0e70bcef1a5d5b2f87289220a51108R21
- the service definition was not OK: https://github.com/felicitus/DunglasApiBundleDemo/pull/1/files#diff-1728bfc1c274f341afc1a0275fca694dR14
- `cascade` wasn't properly configured: https://github.com/felicitus/DunglasApiBundleDemo/pull/1/files#diff-0f7d9a537f1062976ab4c8e2fa39ad72R28

It should be OK now. Can I close?

**Comment by felicitus** [comment]
Yes you can close this, however, it's not clear to me when to use array brackets [] in the service definition as arguments for the "initDenormalizationContext" service and when not. I initially tried without [] and got an error, then I added them which worked for me. Now, with your pull request, it seems to work without [] again.

**Comment by dunglas** [comment]
Before the call, something like the following (which is invalid) was generated:

```
$r->initDenormalizationContext(array(array('groups' => user)));
```
