### ISSUE TITLE
PHP 5.5.0 as minimum requirements ?

### ISSUE THREAD

**Issue by pierrick-vignand** [dunglas/DunglasApiBundle#155]
Is PHP 5.5.0 really the minimum compatible PHP version ?
Compatibility with PHP 5.4 could be great.

**Comment by dunglas** [comment]
Yes it is really required because we use `finally` and `Class::class`. As PHP 5.4 is not supported anymore by the PHP team and will not receiving security updates in 2 months (http://php.net/supported-versions.php) and as Debian stable includes PHP 5.6 by default, we do not plan add 5.4 support except if someone has very good reasons.

**Comment by pierrick-vignand** [comment]
OK, thanks for this information.
