### ISSUE TITLE
Serialize Exception Class Name

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#266]
Right now, when I throw an exception, I don't receive the type of the exception in the resulting JSON-LD output.

It would be nice if the type of the exception could be serialized like this:

```json
hydra:exception: "PartKeepr\\CategoryBundle\\Exceptions\\RootNodeNotFoundException"
```

**Comment by dunglas** [comment]
The exception stack trace (including the exception) is already displayed in debug mode. It should not be displayed outside of the debug mode because it can lead to security issues (at least ease the attacker work).

Btw, the Hydra namespace doesn't define an `exception` property. Custom properties like that must be in a custom namespace.

The exception system should be refactored: #243

**Comment by felicitus** [comment]
I have to think about this. In my project, the exception should be parsed in the frontend to return a proper translated message.

As far as I know, translating exception messages is not good practice.

**Comment by dunglas** [comment]
Yes. It's better to handle the  translation client-side.
