### ISSUE TITLE
Feature request - Extended date filter

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#46]
When using dates, we rarely need filter a collection which has the given date but rather filter by period: before or after a date or between two dates.

### Syntax

Taking into account the change in the way we expose URL as mentioned in the PR #43, we could use the following syntax:

```
url?filter[date][propertyName][after]=value
url?filter[date][propertyName][after]=value
```

Where `value` is a format understandable for the instantiate a `\DateTime` from it.

### Adding support for the year

Sometimes you don't want to look for a specific date but just want to give a year:

```
url?filter[date][createdAt][after]=2005&filter[date][updatedAt][before]=2015
```

Will filter the collection to expose only the items with a `createdAt` date superior or equal to `2006-01-01` and a `updatedAt` date value inferior or equal to `2014-12-32`.

If we do so maybe adding a support for the month would make sense too.

Edit: Adding a support for the month would be logical if we add one for the year, but IMO it would be too much and lead to confusion regarding the format and the use case is specific/rare enough to let the one to add his own filter.

**Comment by sroze** [comment]
Just my opinion about the "year support" and the format. I think that we add to use the ISO 8601 format of datetime and that we shouldn't at all support other formats (such as year only) because the decision to use 00:00:00 or 23:59:59 as time or even 01-01 or 12-31 as day is something that depends on needs.

**Comment by theofidry** [comment]
@sroze What about letting `DateTime` handling that for you? The user would be warned that the only requirement for his date to be valid is to be accepted by `DateTime` aside from edge cases like for the year support. If we follow the ISO 8601 format we have to specify the hour, minutes and seconds which in many cases is unnecessary.

**Comment by dunglas** [comment]
I'm for blindly pass the value to the `DateTime` constructor but advertise only that ISO 8601 dates are supported in the doc.
ISO 8601 should be the preferred way because it's standard (and used in JSON-LD) but this approach give more flexibility for advanced users knowing of the bundle and PHP works internally (we must keep in mind that final users are people consuming the API from various langages such as JavaScript and Ruby).
