### ISSUE TITLE
Search for empty values

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#73]
At first I added this in #70 but I moved it here since it's a different problem although related.

So to sum it up another use case which might happen quite often is to look for "empty" values. I quote the word "empty" since its meaning is a little bit ambigus. Indeed in PHP a value is empty if `undefined`, `null` or a value equivalent to `false`. For this case I'm talking refering to **a value equivalent to `false` which is not null**.

As seen with StrongLoop test in #70, to search for empty value: `?filter[where][property]` or `?filter[where][property]=`

Values matching the criteria for each types, nothing surprising of course:
* string: `""`
* number: `0`
* date: throw an error `Invalid date`
* boolean: `false`

As of now, `?property` or `?property=` is silently ignored from our filters. Would it be possible to change this to look for an empty value instead?

**Comment by dunglas** [comment]
I'm not for adding that behavior: a lot of HTTP clients use that notation because they doesn't property generate URL (they always append query parameters even if it is empty instead of ignoring it).

It's perhaps even in the HTTP RFC. I also think that PHP natively ignore such cases.

Use a custom filter for such needs.

**Comment by theofidry** [comment]
Ok!
